name: build
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        username: '${{ secrets.DOCKER_USER }}'
        password: '${{ secrets.DOCKER_PASS }}'

    - name: Set up docker buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        qemu-version: latest
        buildx-version: latest

    - name: "Build"
      run: make build-extension
